### ISSUE TITLE
Syntax Error(?)

### ISSUE THREAD

**Issue by the-ashh** [jeffreyscheng/Dialgarithm#2]
So, when trying to run Mewtagen for the first time, I get this error: 
![img_0232](https://user-images.githubusercontent.com/16909054/29006018-0a5a075e-7aa5-11e7-9bfa-04169aa586eb.PNG)

I tried importing dialgarithm from pip, but it doesn’t seem exist. Am I doing something wrong?

**Comment by asottile** [comment]
The repository requires python3 -- it appears you're using python 2

**Comment by the-ashh** [comment]
Huh. Ok. Then shouldn’t the readme say something like python3 run.py? 

I did get it running btw
